### ISSUE TITLE
sample.py assumes what input file to sample from

### ISSUE THREAD

**Issue by pechersky** [maxhodak/keras-molecules#16]
Currently, sample.py assumes the presence of a particular h5 file in `data`. Instead, sample.py should take the input data as a parameter. See related pull request.

**Comment by maxhodak** [comment]
I have a branch that overhauls sample.py which I've been meaning to get to finish up but just haven't had time the last couple days: https://github.com/maxhodak/keras-molecules/blob/decoder/sample.py

I'm back though and will get that landed.
