### ISSUE TITLE
Architecture issues

### ISSUE THREAD

**Issue by fchollet** [maxhodak/keras-molecules#4]
Reading your code:

``` python

    def create(self,
               charset,
               original_dim = 120,
               epsilon_std = 0.01,
               latent_rep_size = 292,
               weights_file = None):
        charset_length = len(charset)

        x = Input(shape=(original_dim, charset_length))
        h = Convolution1D(9, 9, input_dim=60)(x)
        h = Convolution1D(9, 9)(h)
        h = Convolution1D(10, 11)(h)
        h = Flatten()(h)
        h = Dense(435)(h)
        z_mean = Dense(latent_rep_size, name='z_mean')(h)
        z_log_var = Dense(latent_rep_size, name='z_log_var')(h)

        def sampling(args):
            z_mean, z_log_var = args
            batch_size = K.shape(z_mean)[0]
            epsilon = K.random_normal(shape=(batch_size, latent_rep_size), mean=0., std=epsilon_std)
            return z_mean + K.exp(z_log_var / 2) * epsilon

        z = Lambda(sampling)([z_mean, z_log_var])

        h = Dense(latent_rep_size, name='latent_input')(z)
        h = RepeatVector(original_dim)(h)
        h = GRU(501, return_sequences = True)(h)
        h = GRU(501, return_sequences = True)(h)
        h = GRU(501, return_sequences = True)(h)
        decoded_mean = TimeDistributedDense(charset_length, activation='softmax', name='decoded_mean')(h)

        def vae_loss(x, x_decoded_mean):
            x = K.flatten(x)
            x_decoded_mean = K.flatten(x_decoded_mean)
            xent_loss = original_dim * objectives.binary_crossentropy(x, x_decoded_mean)
            kl_loss = - 0.5 * K.mean(1 + z_log_var - K.square(z_mean) - K.exp(z_log_var), axis = -1)
            return xent_loss + kl_loss

        encoded_input = Input(shape=(original_dim, latent_rep_size))

        self.autoencoder = Model(x, decoded_mean)
        self.encoder = Model(x, z_mean)
        #self.decoder = Model(self.autoencoder.get_layer('latent_input')(encoded_input),
        #                     self.autoencoder.get_layer('decoded_mean')(encoded_input))
```
- What you call `original_dim` should actually be called something like `max_length`
- You pass an `input_dim` argument to the first conv layer, this is not necessary (you already have an Input layer and you're using the functional API anyway)
- Your conv layers do not have activations! You should add an argument `activation='relu'` to all of them.
- Same for most of your `Dense`layers. Except these two, for which a linear layer makes sense:

``` python
z_mean = Dense(latent_rep_size, name='z_mean')(h)
z_log_var = Dense(latent_rep_size, name='z_log_var')(h)
```

**Comment by fchollet** [comment]
Also the commented-out line for the decoder could not work. Setting up the decoder requires access to every intermediate layer between `z_mean` and `decoded_mean`.

**Comment by maxhodak** [comment]
Cool, thanks for this review. I'll add the activations!

For the decoder, I'm not totally sure I understand how that should be wired up. I know that commented-out line is wrong. Per your comment, would it be:

```
decoder = Model(autoencoder.get_layer('z_mean'),
                autoencoder.get_layer('decoded_mean')(encoded_input))
```

**Comment by maxhodak** [comment]
I've landed 156fb6c which I believe addresses most of these comments.

**Comment by maxhodak** [comment]
@fchollet it looks like the autoencoder works well but when I try and run the encoder / decoder models separately something really weird is happening. It might be that I just don't understand how to wire up the model. I've put together a summary of the issue I'm seeing in a notebook here: https://github.com/maxhodak/keras-molecules/blob/decoder/debugging.ipynb

**Comment by maxhodak** [comment]
I've updated my model per your comments on this branch: https://github.com/maxhodak/keras-molecules/blob/decoder/autoencoder/model.py

**Comment by tantrev** [comment]
Is it possible that using that the GTX 1080's single precision may also be producing different results than a double-precision run?

**Comment by maxhodak** [comment]
I figured it out, it was a scoping issue.
