### ISSUE TITLE
Cannot fetch LFS-stored files.

### ISSUE THREAD

**Issue by lejar** [maxhodak/keras-molecules#46]
The files in data/ cannot be retrieved via git lfs, because the bandwidth quota seems to be exceeded (see error message below). Is there an alternate method of obtaining the files?
```
keras-molecules$ git lfs fetch
Fetching master
Git LFS: (0 of 3 files) 0 B / 156.20 MB                                                                                                                                                                            
batch response: http: This repository is over its data quota. Purchase more data packs to restore access.
Docs: https://help.github.com/articles/purchasing-additional-storage-and-bandwidth-for-a-personal-account/
Warning: errors occurred
```

**Comment by hsiaoyi0504** [comment]
I have the same issue. Maybe we can try move them to Google Drive, DropBox, Box.net or Microsoft's Visual Studio Online, as mentioned in [Stéphane Peter's Blog](https://medium.com/@megastep/github-s-large-file-storage-is-no-panacea-for-open-source-quite-the-opposite-12c0e16a9a91#.otukm94ch).

**Comment by hsiaoyi0504** [comment]
It seems that it works again, but I think it is really a issue.

**Comment by hsiaoyi0504** [comment]
I created a temporary gitlab repo for this. 
[https://gitlab.com/hsiaoyi0504/keras-molecules-data/tree/master](https://gitlab.com/hsiaoyi0504/keras-molecules-data/tree/master)
But I don't know what is the bandwidth and storage quotas of git LFS support on gitLab.com.

**Comment by maxhodak** [comment]
This should be fixed now, right? I bought a data pack a few weeks ago.

**Comment by hsiaoyi0504** [comment]
Yep, it already worked.
